// SPDX-License-Identifier: Apache-2.0
// #1265 — Port the brainstorm terminal-state guardrail dual-sided: target
// projects generated by arbiter must receive the brainstorming skill, the
// post-brainstorm-stop hook (wired into the dispatcher at L2+), and the
// terminal-state rule. Self-side (#699) already shipped; these tests pin the
// generated/template side.
import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { mkdtempSync, readFileSync, existsSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { generateClaude } from '../../src/generators/claude.js'
import { generateSkills } from '../../src/generators/skills.js'
import { renderTemplate } from '../../src/utils/render.js'
import { makeConfig } from '../helpers.js'

describe('#1265 brainstorm guardrail — skill generation', () => {
  let dir: string

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'arbiter-brainstorm-'))
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  it('generateSkills emits the brainstorming SKILL.md for claude projects', () => {
    const config = makeConfig(dir, { tools: ['claude'] })
    generateSkills(config, [])
    const skillPath = join(dir, '.claude', 'skills', 'brainstorming', 'SKILL.md')
    expect(existsSync(skillPath)).toBe(true)
  })

  it('brainstorming skill states the MANDATORY terminal state (no auto-implementation)', () => {
    const config = makeConfig(dir, { tools: ['claude'] })
    generateSkills(config, [])
    const content = readFileSync(
      join(dir, '.claude', 'skills', 'brainstorming', 'SKILL.md'),
      'utf-8',
    )
    expect(content).toMatch(/terminal state/i)
    expect(content).toContain('brainstorm-active')
    expect(content).toMatch(/design doc/i)
  })
})

describe('#1265 brainstorm guardrail — hook generation + dispatch (L2+)', () => {
  let dir: string

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'arbiter-brainstorm-hook-'))
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  it('emits post-brainstorm-stop.mjs into .claude/hooks at L2', () => {
    generateClaude(makeConfig(dir, { governanceLevel: 'L2' }))
    expect(existsSync(join(dir, '.claude', 'hooks', 'post-brainstorm-stop.mjs'))).toBe(true)
  })

  it('dispatcher wires post-brainstorm-stop.mjs into UserPromptSubmit at L2', () => {
    const out = renderTemplate(
      'claude/hooks/hooks.mjs.ejs',
      makeConfig('/tmp/x', { governanceLevel: 'L2' }) as unknown as Record<string, unknown>,
    )
    expect(out).toContain('post-brainstorm-stop.mjs')
    // It must live under the UserPromptSubmit handler list
    const upsIdx = out.indexOf('UserPromptSubmit')
    const hookIdx = out.indexOf('post-brainstorm-stop.mjs')
    expect(upsIdx).toBeGreaterThan(-1)
    expect(hookIdx).toBeGreaterThan(upsIdx)
  })

  it('dispatcher does NOT reference post-brainstorm-stop.mjs at L1', () => {
    const out = renderTemplate(
      'claude/hooks/hooks.mjs.ejs',
      makeConfig('/tmp/x', { governanceLevel: 'L1' }) as unknown as Record<string, unknown>,
    )
    expect(out).not.toContain('post-brainstorm-stop.mjs')
  })
})

describe('#1265 brainstorm guardrail — terminal-state rule', () => {
  let dir: string

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'arbiter-brainstorm-rule-'))
  })

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  it('emits the brainstorm terminal-state rule into .claude/rules', () => {
    generateClaude(makeConfig(dir))
    const rulePath = join(dir, '.claude', 'rules', '55-brainstorm-terminal-state.md')
    expect(existsSync(rulePath)).toBe(true)
    const content = readFileSync(rulePath, 'utf-8')
    expect(content).toMatch(/never auto-implement|no auto-implementation|never.*implement/i)
    expect(content).toContain('brainstorm-active')
  })
})
