#!/usr/bin/env node
// Arbiter hook dispatcher — routes events to registered handlers (#248)
// FAIL-OPEN-INTENT: dispatcher propagates handler exit codes; no top-level catch needed
// Hook type: any — registered in settings.json as the single entry per event
// Usage: node .claude/hooks/hooks.mjs <EventType:Matcher>
// Config table drives which handler scripts run per event.
// Brownfield: this file is skipIfExists — user customisations are preserved.
// Generated by arbiter for project: arbiter
import { spawnSync } from 'node:child_process'
import { readFileSync, existsSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))

/**
 * Config table: maps "EventType:Matcher" -> ordered list of handler filenames.
 * Handlers run sequentially; first non-zero exit aborts the chain.
 * Handlers that read stdin receive the same buffered payload.
 */
const HANDLERS = {
  'PreToolUse:Bash': ['stop-dangerous.mjs', 'enforce-gate-before-pr.mjs'],
  'PreToolUse:Edit|Write': [
    'enforce-read-only.mjs',
    'pre-edit-ssot-guard.mjs',
    'pre-edit-plan-anchor.mjs',
  ],
  'PreToolUse:Task|Agent': ['pre-spawn-worktree-guard.mjs'],
  'PostToolUse:Bash': ['post-commit-check.mjs'],
  'PostToolUse:Edit|Write': [
    'check-no-orphan-todo.mjs',
    'check-no-placeholders.mjs',
    'check-no-skipped-tests.mjs',
    'check-no-pii.mjs',
    'check-no-raw-types.mjs',
    'check-no-mockmvc.mjs',
    'post-edit-dispatch.mjs',
  ],
  'PostToolUseFailure:Bash': ['debug-state-on-failure.mjs'],
  PreCompact: ['pre-compact.mjs'],
  SubagentStop: ['post-subagent-release.mjs'],
  'PostToolUse:ExitPlanMode': ['exitplanmode-banner.mjs'],
  UserPromptSubmit: ['skill-forced-eval.mjs', 'guard-task-completion.mjs'],
  Stop: ['stop-evidence-guard.mjs', 'stop-finding-loss.mjs'],
}

const eventKey = process.argv[2] ?? ''
const handlers = HANDLERS[eventKey] ?? []

if (handlers.length === 0) process.exit(0)

// Buffer stdin once — passed to every handler that may need it
let stdinData = Buffer.alloc(0)
try {
  stdinData = readFileSync(0)
} catch {
  // stdin may not be available (PreToolUse events) — expected
}

for (const handler of handlers) {
  const handlerPath = join(__dirname, handler)
  if (!existsSync(handlerPath)) {
    process.stderr.write(`[hooks.mjs] Registered handler is missing: ${handlerPath}\n`)
    process.exit(2)
  }

  const result = spawnSync('node', [handlerPath], {
    input: stdinData,
    stdio: ['pipe', 'inherit', 'inherit'],
    env: process.env,
  })

  if (result.status !== 0 && result.status !== null) {
    process.exit(result.status)
  }
  if (result.signal) {
    process.stderr.write(`[hooks.mjs] Handler ${handler} killed by signal ${result.signal}\n`)
    process.exit(2)
  }
}
