// SPDX-License-Identifier: Apache-2.0
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createTestProject, cleanupTestProject } from '../helpers.js'
import { runUpdate } from '../../src/commands/update.js'
import { DEFAULT_THRESHOLDS } from '../../src/config/schema.js'

// ── #1980: `arbiter update` must not overwrite a file that carries its own ────
// preserve/do-not-edit marker. A governed repo may replace a generated file
// (e.g. GLOBAL_INVARIANTS.md) with a deliberate hand-maintained pointer stub
// marked `arbiter:preserve`; `update` previously overwrote it unconditionally
// because GLOBAL_INVARIANTS.md is written with `backup: true` but no
// `skipIfExists`, so it never reached the withheld-file logic at all.

function writeV2Config(dir: string, overrides: Record<string, unknown> = {}): void {
  const config = {
    version: '0.2',
    tools: ['claude'],
    governanceLevel: 'L2',
    useGitHub: false,
    features: {
      contractTesting: false,
      mutationTesting: false,
      securityScanning: true,
      evidenceHarness: false,
      debtGates: true,
      suppressions: true,
    },
    thresholds: { ...DEFAULT_THRESHOLDS.L2 },
    // 'security' is an optional invariant tier — required for
    // GLOBAL_INVARIANTS.md to be emitted at all (see generateGlobalInvariants).
    invariantTiers: ['architectural', 'governance', 'security'],
    ...overrides,
  }
  writeFileSync(join(dir, 'arbiter.json'), JSON.stringify(config, null, 2))
}

describe('runUpdate — preserve marker withholds overwrite (#1980)', () => {
  let dir: string

  beforeEach(() => {
    dir = createTestProject('typescript')
    vi.spyOn(console, 'log').mockImplementation(() => undefined)
  })

  afterEach(() => {
    vi.restoreAllMocks()
    cleanupTestProject(dir)
  })

  it('leaves a marked GLOBAL_INVARIANTS.md byte-identical across update', async () => {
    writeV2Config(dir)
    // First update materializes the real generated file.
    await runUpdate({ dir, json: true, github: false })

    const target = join(dir, 'GLOBAL_INVARIANTS.md')
    const stub =
      '<!-- arbiter:preserve -->\n' +
      '# GLOBAL_INVARIANTS.md\n\n' +
      'Hand-maintained pointer stub. Do not edit this file — see the central docs.\n'
    writeFileSync(target, stub)

    // Force a full regen so GLOBAL_INVARIANTS.md is re-rendered and would
    // normally be overwritten (it has no skipIfExists guard).
    writeV2Config(dir, { governanceLevel: 'L3' })
    const result = await runUpdate({ dir, json: true, github: false })

    expect(result.keysRun?.has('*')).toBe(true)
    expect(readFileSync(target, 'utf-8')).toBe(stub)
  })
})

// ── #2120: `.claude/settings.json` was the one emitted file NO protection ─────
// mechanism reached. `generateClaudeSettings` did its own merge, its own
// disk-compare, its own copyFileSync backup and its own writeFileSync — so the
// generated manifest never learned its hash, `arbiter:preserve` never applied,
// and neither did the adopt/plan machinery. JSON has no comments, but the
// whole-file marker is a substring test, so an ordinary key carries it.
describe('runUpdate — .claude/settings.json honours the preserve marker (#2120)', () => {
  let dir: string

  beforeEach(() => {
    dir = createTestProject('typescript')
    vi.spyOn(console, 'log').mockImplementation(() => undefined)
  })

  afterEach(() => {
    vi.restoreAllMocks()
    cleanupTestProject(dir)
  })

  it('leaves a marked settings.json byte-identical across a full regen', async () => {
    writeV2Config(dir)
    await runUpdate({ dir, json: true, github: false })

    const target = join(dir, '.claude', 'settings.json')
    const stub = JSON.stringify({ _arbiter: 'arbiter:preserve', hooks: {} }, null, 2) + '\n'
    writeFileSync(target, stub)

    writeV2Config(dir, { governanceLevel: 'L3' })
    const result = await runUpdate({ dir, json: true, github: false })

    expect(result.keysRun?.has('*')).toBe(true)
    expect(readFileSync(target, 'utf-8')).toBe(stub)
  })

  it('an unmarked settings.json still receives the merge (protection is opt-in)', async () => {
    writeV2Config(dir)
    await runUpdate({ dir, json: true, github: false })

    const target = join(dir, '.claude', 'settings.json')
    writeFileSync(target, JSON.stringify({ hooks: {} }, null, 2) + '\n')

    writeV2Config(dir, { governanceLevel: 'L3' })
    await runUpdate({ dir, json: true, github: false })

    const after = JSON.parse(readFileSync(target, 'utf-8')) as { hooks: Record<string, unknown> }
    expect(Object.keys(after.hooks).length).toBeGreaterThan(0)
  })
})
