// SPDX-License-Identifier: Apache-2.0
/**
 * Creates GitHub issues for each W1 (partial) dimension in the wave plan.
 * Uses run-cli.ts (CANON-12) — no direct child_process usage.
 *
 * In dry-run mode: logs intended calls but does NOT invoke runCli.
 *
 * Issue: #1043
 */

import type { WavePlan } from './wave-engine.js'
import { runCli } from '../utils/run-cli.js'

export interface EmitResult {
  created: number
  skipped: number
}

export function emitWaveIssues(plan: WavePlan, dryRun: boolean): EmitResult {
  const w1 = plan.waves.find((w) => w.label === 'W1')?.dimensions ?? []

  if (dryRun) {
    for (const entry of w1) {
      process.stderr.write(`[dry-run] would create issue: kit(#1043): enforce ${entry.dimId}\n`)
    }
    return { created: 0, skipped: w1.length }
  }

  let created = 0
  for (const entry of w1) {
    const body = `KIT dimension \`${entry.dimId}\` (category: ${entry.category}) requires enforcement.\n\nGenerated by: \`arbiter kit install --emit-issues\``
    runCli('gh', [
      'issue',
      'create',
      '--title',
      `kit(#1043): enforce ${entry.dimId}`,
      '--label',
      'kit',
      '--body',
      body,
    ])
    created++
  }

  return { created, skipped: 0 }
}
