// SPDX-License-Identifier: Apache-2.0
/**
 * Creates GitHub issues for each W1 (partial) dimension in the wave plan.
 * Uses run-cli.ts (CANON-12) — no direct child_process usage.
 *
 * In dry-run mode: logs intended calls but does NOT invoke runCli.
 *
 * Idempotent: before creating, the existing `kit`-labelled issues are queried and
 * any dimension whose title already exists is skipped, so re-running
 * `kit install --emit-issues` does not duplicate issues (#1575). Each create is
 * wrapped so one failure does not abort the rest; failures are surfaced in the
 * returned `failed` count rather than thrown.
 *
 * Issue: #1043
 */

import type { WavePlan } from './wave-engine.js'
import { runCli } from '../utils/run-cli.js'

export interface EmitResult {
  /** Issues newly created this run. */
  created: number
  /** Issues skipped because an issue with the same title already existed (or, in
   *  dry-run, the count that would have been created). */
  skipped: number
  /** Creates that errored (e.g. `gh` not authenticated / API failure). */
  failed: number
}

/** Stable issue title for a W1 dimension — the dedup key. */
function issueTitle(dimId: string): string {
  return `kit(#1043): enforce ${dimId}`
}

/**
 * Best-effort set of titles of already-existing `kit`-labelled issues. Queries
 * `gh issue list` once; on any failure (gh missing/unauthenticated, unparseable
 * output) returns an empty set so emission still proceeds — dedup is a safety net,
 * not a hard precondition.
 */
function fetchExistingTitles(): Set<string> {
  try {
    const { stdout } = runCli('gh', [
      'issue',
      'list',
      '--label',
      'kit',
      '--state',
      'all',
      '--limit',
      '500',
      '--json',
      'title',
    ])
    const parsed: unknown = JSON.parse(stdout)
    if (!Array.isArray(parsed)) return new Set()
    const titles = new Set<string>()
    for (const item of parsed) {
      const title = (item as { title?: unknown }).title
      if (typeof title === 'string') titles.add(title)
    }
    return titles
  } catch (err) {
    // Best-effort dedup: surface the failure so a silently-skipped title fetch (which
    // would let duplicate issues be created) is observable, then degrade to empty.
    const reason = err instanceof Error ? err.message : String(err)
    process.stderr.write(
      `[emit-issues] could not fetch existing issue titles — dedup skipped: ${reason}\n`,
    )
    return new Set()
  }
}

export function emitWaveIssues(plan: WavePlan, dryRun: boolean): EmitResult {
  const w1 = plan.waves.find((w) => w.label === 'W1')?.dimensions ?? []

  if (dryRun) {
    for (const entry of w1) {
      process.stderr.write(`[dry-run] would create issue: ${issueTitle(entry.dimId)}\n`)
    }
    return { created: 0, skipped: w1.length, failed: 0 }
  }

  // Nothing to emit — do not even query GitHub.
  if (w1.length === 0) return { created: 0, skipped: 0, failed: 0 }

  const existing = fetchExistingTitles()
  let created = 0
  let skipped = 0
  let failed = 0
  for (const entry of w1) {
    const title = issueTitle(entry.dimId)
    if (existing.has(title)) {
      process.stderr.write(`[emit-issues] skip (already exists): ${title}\n`)
      skipped++
      continue
    }
    const body = `KIT dimension \`${entry.dimId}\` (category: ${entry.category}) requires enforcement.\n\nGenerated by: \`arbiter kit install --emit-issues\``
    try {
      runCli('gh', ['issue', 'create', '--title', title, '--label', 'kit', '--body', body])
      created++
      // Guard against duplicate dimIds within the same plan.
      existing.add(title)
    } catch (err) {
      process.stderr.write(
        `[emit-issues] FAILED to create "${title}": ${err instanceof Error ? err.message : String(err)}\n`,
      )
      failed++
    }
  }

  return { created, skipped, failed }
}
