// SPDX-License-Identifier: Apache-2.0
// #1835: `arbiter init` can emit a scripts/check-*.mjs gate that nothing ever
// invokes — a "scaffolded ceremony" ghost (field evidence: 11 orphaned scripts,
// ~1133 LOC, in a real arbiter-generated project). arbiter's own repo has a
// thorough self-check for this (scripts/check-emission-coherence.mjs, INV-123),
// but that tool ships in arbiter's OWN tree only — it is never bundled into
// `dist/`, so `arbiter doctor` run against an already-generated target project
// (including ones generated by an older arbiter version, before a wiring fix
// landed) cannot see it. This is the doctor-side, ships-in-the-CLI counterpart:
// a lightweight, permanent detector for every project arbiter has ever scaffolded.
//
// Scope is deliberately narrower than the self-check: only the three reference
// surfaces the field evidence actually implicated (check-all.mjs, run.sh,
// Makefile) are scanned, and only scripts/check-*.mjs candidates are considered
// (the class of file the evidence was about). This is advisory scaffolding
// health, not a strict gate — see checkScaffoldWiring in commands/doctor.ts.
import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

interface UnwiredScaffold {
  /** Repo-relative path, e.g. "scripts/check-foo.mjs". */
  path: string
}

export interface ScaffoldWiringReport {
  /** scripts/check-*.mjs files present on disk but referenced by none of the
   * scanned surfaces (check-all.mjs, run.sh, Makefile). */
  unwired: UnwiredScaffold[]
}

function readIfExists(dir: string, rel: string): string | null {
  const abs = join(dir, rel)
  if (!existsSync(abs)) return null
  try {
    return readFileSync(abs, 'utf-8')
    // FAIL-OPEN-INTENT: advisory health check — an unreadable/deleted file just drops out of the corpus.
  } catch {
    return null
  }
}

/** scripts/check-*.mjs files present under `dir`, excluding check-all.mjs itself. */
function listCheckScripts(dir: string): string[] {
  const scriptsDir = join(dir, 'scripts')
  if (!existsSync(scriptsDir)) return []
  let entries: string[]
  try {
    entries = readdirSync(scriptsDir)
    // FAIL-OPEN-INTENT: advisory health check — an unreadable scripts/ dir reports "nothing to check".
  } catch {
    return []
  }
  return entries
    .filter((f) => /^check-.*\.mjs$/.test(f) && f !== 'check-all.mjs')
    .sort()
    .map((f) => `scripts/${f}`)
}

/**
 * Scan a (possibly already-generated) project directory for scripts/check-*.mjs
 * files that check-all.mjs / run.sh / Makefile never reference by name. Pure,
 * read-only, dir-parameterized — safe to call from `doctor health` on any target.
 * Missing surfaces (no run.sh, no Makefile) are simply absent from the corpus,
 * never an error.
 */
export function checkScaffoldWiring(dir: string): ScaffoldWiringReport {
  const candidates = listCheckScripts(dir)
  if (candidates.length === 0) return { unwired: [] }

  const corpus = [
    readIfExists(dir, join('scripts', 'check-all.mjs')),
    readIfExists(dir, 'run.sh'),
    readIfExists(dir, 'Makefile'),
  ].filter((c): c is string => c !== null)

  const unwired = candidates
    .filter((rel) => {
      const name = rel.slice('scripts/'.length)
      return !corpus.some((content) => content.includes(name))
    })
    .map((path) => ({ path }))

  return { unwired }
}
