// SPDX-License-Identifier: Apache-2.0
import type { StackAdapter } from './StackAdapter.js'
import type { LanguageHook } from '../wizard/types.js'
import { registerAdapter } from './_registry.js'

const tsAdapter: StackAdapter = {
  language: 'typescript',
  isStub: false,
  lintCommand: () => 'npx eslint src __tests__',
  formatCommand: () => 'npx prettier --write .',
  languageHooks: (): LanguageHook[] => [
    {
      name: 'check-no-any.mjs',
      description: 'Blocks TypeScript `any` type usage (INV-04)',
      body: '// generated by arbiter typescript adapter\n// see src/adapters/typescript.ts',
    },
  ],
  supportsCoverage: () => true,
  supportsMutation: () => true,
}

registerAdapter(tsAdapter)
export { tsAdapter }
