// SPDX-License-Identifier: Apache-2.0
/**
 * Aider agent-rules emitter (#265).
 *
 * Output: `CONVENTIONS.md`
 * Format: Markdown conventions file.
 */

import type { AgentRulesIntermediate } from '../intermediate.js'

export function emitAider(intermediate: AgentRulesIntermediate): string {
  const lines: string[] = []

  lines.push(`# ${intermediate.repo} — Conventions`)
  lines.push('')
  lines.push('> Auto-generated by `arbiter agent-rules export --target aider`.')
  lines.push('')
  lines.push('## Governance Invariants')
  lines.push('')

  for (const inv of intermediate.invariants) {
    const tag = inv.severity === 'hard-stop' ? '[MANDATORY]' : '[RECOMMENDED]'
    lines.push(`- ${tag} **${inv.id}**: ${inv.statement}`)
  }

  lines.push('')
  lines.push('## Workflows')
  lines.push('')
  for (const wf of intermediate.workflows) {
    lines.push(`- ${wf.trigger}: ${wf.action}`)
  }
  lines.push('')

  return lines.join('\n')
}
