// SPDX-License-Identifier: Apache-2.0
/**
 * Claude agent-rules emitter (#265).
 *
 * Output: `.claude/AGENT_RULES.md`
 * Format: Markdown with INV table, split by severity.
 */

import type { AgentRulesIntermediate } from '../intermediate.js'

export function emitClaude(intermediate: AgentRulesIntermediate): string {
  const lines: string[] = []

  lines.push(`# ${intermediate.repo} — Agent Rules (Claude Code)`)
  lines.push('')
  lines.push('> Auto-generated by `arbiter agent-rules export --target claude`.')
  lines.push('> Do not edit manually — re-run the command to refresh.')
  lines.push('')
  lines.push('## Invariants')
  lines.push('')

  const mandatory = intermediate.invariants.filter((i) => i.severity === 'hard-stop')
  const advisory = intermediate.invariants.filter((i) => i.severity === 'advisory')

  if (mandatory.length > 0) {
    lines.push('### MANDATORY (hard-stop)')
    lines.push('')
    lines.push('Violating these rules is a hard stop — do not proceed past verification.')
    lines.push('')
    lines.push('| ID | Rule | Enforcement |')
    lines.push('|----|------|-------------|')
    for (const inv of mandatory) {
      const enforcement =
        inv.enforcement.length > 0
          ? inv.enforcement.map((e) => `\`${e.ref}\``).join(', ')
          : '_(none declared)_'
      lines.push(`| **${inv.id}** | ${inv.statement} | ${enforcement} |`)
    }
    lines.push('')
  }

  if (advisory.length > 0) {
    lines.push('### RECOMMENDED (advisory)')
    lines.push('')
    lines.push('| ID | Rule | Enforcement |')
    lines.push('|----|------|-------------|')
    for (const inv of advisory) {
      const enforcement =
        inv.enforcement.length > 0
          ? inv.enforcement.map((e) => `\`${e.ref}\``).join(', ')
          : '_(none declared)_'
      lines.push(`| ${inv.id} | ${inv.statement} | ${enforcement} |`)
    }
    lines.push('')
  }

  lines.push('## Workflows')
  lines.push('')
  for (const wf of intermediate.workflows) {
    lines.push(`- **${wf.trigger}**: ${wf.action}`)
  }
  lines.push('')

  return lines.join('\n')
}
