/**
 * GitHub Copilot agent-rules emitter (#265).
 *
 * Output: `.github/copilot-instructions.md`
 * Format: Markdown with sections for hard-stops and advisory rules.
 */

import type { AgentRulesIntermediate } from '../intermediate.js'

export function emitCopilot(intermediate: AgentRulesIntermediate): string {
  const lines: string[] = []

  lines.push(`# ${intermediate.repo} — Copilot Instructions`)
  lines.push('')
  lines.push('> Auto-generated by `arbiter agent-rules export --target copilot`.')
  lines.push('')
  lines.push('## Governance Rules')
  lines.push('')

  const mandatory = intermediate.invariants.filter((i) => i.severity === 'hard-stop')
  const advisory = intermediate.invariants.filter((i) => i.severity === 'advisory')

  if (mandatory.length > 0) {
    lines.push('### Do NOT violate (hard stops)')
    lines.push('')
    for (const inv of mandatory) {
      lines.push(`- **${inv.id}** — ${inv.statement}`)
    }
    lines.push('')
  }

  if (advisory.length > 0) {
    lines.push('### Follow by default (advisory)')
    lines.push('')
    for (const inv of advisory) {
      lines.push(`- ${inv.id} — ${inv.statement}`)
    }
    lines.push('')
  }

  lines.push('## Task Workflow')
  lines.push('')
  for (const wf of intermediate.workflows) {
    lines.push(`- ${wf.trigger}: ${wf.action}`)
  }
  lines.push('')

  return lines.join('\n')
}
