#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// scripts/conformance.mjs — generated by arbiter (#1398, INV-128).
// Conformance scorecard runner for this project.
// Delegates to `arbiter conformance` via npx (no local install required).
//
// Usage: node scripts/conformance.mjs [--check] [--format=<json|text>] [--help]
//
// Exit codes (INV-53): 0=PASS, 1=FAIL (conformance below threshold), 2=ERROR.
// When invoked by check-all.mjs (advisory, L2): exit codes are informational;
// the gate never hard-fails on conformance result alone.
import { spawnSync } from 'node:child_process'

const args = process.argv.slice(2)

const result = spawnSync('npx', ['--no-install', 'arbiter', 'conformance', ...args], {
  stdio: 'inherit',
  encoding: 'utf-8',
})

if (result.error) {
  process.stderr.write(
    `[conformance] spawn error: ${result.error.message}\n`,
  )
  process.exit(2)
}

process.exit(result.status ?? 1)
