// SPDX-License-Identifier: Apache-2.0
// RED phase (#2221) — end-to-end reproducer of the Consumer Reliability Bar red:
// a hook arbiter retired (deleted from the framework) survives in every consumer
// generated by an older version, and the target's own `check-hook-routing.mjs`
// reports `DEAD Arbiter-owned hook <file>` on every run, forever. `arbiter update`
// must RETIRE the pristine orphan (and only the pristine one).
import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { execFileSync, spawnSync } from 'node:child_process'
import { createHash } from 'node:crypto'
import { runInit } from '../../src/commands/init.js'
import { runUpdate } from '../../src/commands/update.js'
import { loadGeneratedManifest, saveGeneratedManifest } from '../../src/state/generated-manifest.js'
import { RETIRED_RENDERS } from '../../src/state/retired-renders.js'

const ORPHAN = '.claude/hooks/pre-task-track-detect.mjs'
// The `Arbiter hook:` marker is what `check-hook-routing.mjs` uses to claim
// ownership of an on-disk file, independent of the manifest — which is why
// dropping the manifest key alone never clears the DEAD finding.
const ORPHAN_BODY =
  '#!/usr/bin/env node\n// Arbiter hook: retired track detector\nprocess.exit(0)\n'

const sha = (s: string): string => createHash('sha256').update(s).digest('hex')

function initGit(dir: string): void {
  for (const args of [
    ['init'],
    ['config', 'user.email', 'test@test.com'],
    ['config', 'user.name', 'Test'],
  ]) {
    execFileSync('git', args, { cwd: dir, stdio: 'ignore' })
  }
}

/** Run the target's OWN emitted routing check, exactly as the reliability bar does. */
function routingCheck(dir: string): { status: number | null; stderr: string } {
  const result = spawnSync('node', [join(dir, 'scripts', 'check-hook-routing.mjs')], {
    cwd: dir,
    encoding: 'utf-8',
    timeout: 120000,
  })
  return { status: result.status, stderr: String(result.stderr ?? '') }
}

/** Plant a retired arbiter-owned hook with the given on-disk body, recorded as pristine. */
function plantOrphan(dir: string, body: string, recordedHash: string): void {
  writeFileSync(join(dir, ORPHAN), body)
  const manifest = loadGeneratedManifest(dir)
  manifest[ORPHAN] = recordedHash
  saveGeneratedManifest(dir, manifest)
}

describe('#2221 update retires framework-retired arbiter-owned files', () => {
  let dir: string

  beforeEach(async () => {
    dir = mkdtempSync(join(tmpdir(), 'arb-2221-'))
    initGit(dir)
    await runInit({
      yes: true,
      tools: 'claude',
      level: 'L2',
      dir,
      noVerify: true,
      language: 'typescript',
    })
  })
  afterEach(() => {
    rmSync(dir, { recursive: true, force: true })
  })

  it('AC1: deletes a PRISTINE orphan hook and the routing check goes from red to green', async () => {
    plantOrphan(dir, ORPHAN_BODY, sha(ORPHAN_BODY))

    // The reproducer: the target's own gate check is RED before the fix.
    const before = routingCheck(dir)
    expect(before.status).toBe(1)
    expect(before.stderr).toContain('DEAD Arbiter-owned hook pre-task-track-detect.mjs')

    await runUpdate({ dir, github: false })

    expect(existsSync(join(dir, ORPHAN))).toBe(false)
    const after = routingCheck(dir)
    expect(after.stderr).not.toContain('DEAD Arbiter-owned hook pre-task-track-detect.mjs')
    expect(after.status).toBe(0)
    expect(loadGeneratedManifest(dir)[ORPHAN]).toBeUndefined()
  })

  it('AC2: a USER-MODIFIED orphan is preserved, never deleted', async () => {
    const edited = `${ORPHAN_BODY}// local edit\n`
    // Recorded hash is arbiter's render; disk carries the user's edit → diverged.
    plantOrphan(dir, edited, sha(ORPHAN_BODY))

    await runUpdate({ dir, github: false })

    expect(existsSync(join(dir, ORPHAN))).toBe(true)
    expect(readFileSync(join(dir, ORPHAN), 'utf-8')).toBe(edited)
  })

  // The go consumer shape: the orphan is on disk and the repo has NO manifest
  // entry for it — the manifest-only rule never reaches it. Ownership is proved
  // instead by byte-identity to a render arbiter itself emitted.
  it('AC4: retires an unrecorded orphan whose bytes match a known arbiter render', async () => {
    const known = readFileSync(
      join(process.cwd(), '__tests__', 'fixtures', 'retired-renders', 'pre-task-track-detect.mjs'),
      'utf-8',
    )
    // The fixture IS the render the registry pins — if this drifts, the registry
    // hash is wrong and every claim built on it is void.
    expect(sha(known)).toBe(RETIRED_RENDERS[ORPHAN]?.[0])
    writeFileSync(join(dir, ORPHAN), known)
    const manifest = loadGeneratedManifest(dir)
    expect(manifest[ORPHAN]).toBeUndefined()

    const before = routingCheck(dir)
    expect(before.status).toBe(1)
    expect(before.stderr).toContain('DEAD Arbiter-owned hook pre-task-track-detect.mjs')

    await runUpdate({ dir, github: false })

    expect(existsSync(join(dir, ORPHAN))).toBe(false)
    expect(routingCheck(dir).status).toBe(0)
  })

  it('AC5: an unrecorded orphan that matches no known render is preserved', async () => {
    writeFileSync(join(dir, ORPHAN), `${ORPHAN_BODY}// hand-written by the project\n`)
    await runUpdate({ dir, github: false })
    expect(existsSync(join(dir, ORPHAN))).toBe(true)
  })

  it('AC3: a still-emitted hook is untouched by retirement', async () => {
    const live = join(dir, '.claude', 'hooks', 'stop-dangerous.mjs')
    expect(existsSync(live)).toBe(true)
    await runUpdate({ dir, github: false })
    expect(existsSync(live)).toBe(true)
  })
})
