// debt-lib.mjs — generated by arbiter
// Shared metric collection helpers used by capture-debt-baseline.mjs and debt-report.mjs.
// Re-generate with: arbiter update
import { spawnSync } from 'node:child_process'
import { readFileSync, existsSync, readdirSync } from 'node:fs'
import { resolve } from 'node:path'

function run(cmd, args, opts) {
  return spawnSync(cmd, args, { encoding: 'utf-8', shell: false, ...opts })
}

/**
 * Run a command. If the binary is not installed (ENOENT), log a warning to
 * stderr and return null. Callers skip null-result metrics entirely.
 * @param {string} name - metric key for the warning message
 * @param {string} tool - human name of the missing tool
 * @param {string} cmd  - executable
 * @param {string[]} args
 * @param {object} [opts]
 * @returns {import('child_process').SpawnSyncReturns<string> | null}
 */
export function spawnOrSkip(name, tool, cmd, args, opts) {
  const r = run(cmd, args, opts ?? {})
  if (r.error?.code === 'ENOENT') {
    process.stderr.write(`[baseline] skip ${name} — ${tool} not installed\n`)
    return null
  }
  return r
}

/**
 * Count TODO comments across common source file extensions in cwd.
 * @param {string} cwd
 * @returns {number}
 */
export function countTodos(cwd) {
  const r = run(
    'grep',
    [
      '-r',
      '--include=*.js',
      '--include=*.ts',
      '--include=*.java',
      '--include=*.go',
      '--include=*.py',
      '--include=*.rs',
      '-l',
      'TODO',
      '.',
    ],
    { cwd },
  )
  if (r.status !== 0) return 0
  const files = (r.stdout ?? '').trim().split('\n').filter(Boolean)
  let count = 0
  for (const f of files) {
    try {
      const lines = readFileSync(resolve(cwd, f), 'utf-8').split('\n')
      count += lines.filter((l) => /\bTODO\b/.test(l)).length
    } catch {
      /* skip unreadable files */
    }
  }
  return count
}

/**
 * Return the short git commit hash for HEAD, or 'unknown'.
 * @param {string} cwd
 * @returns {string}
 */
export function getCommit(cwd) {
  const r = run('git', ['rev-parse', '--short', 'HEAD'], { cwd })
  return r.status === 0 ? r.stdout.trim() : 'unknown'
}

// ─── Per-stack metric collectors ─────────────────────────────────────────────
// Each language block exports a single `collectMetrics(cwd)` function.
// EJS conditionals select the correct block at generation time.

/**
 * Collect TypeScript/JavaScript debt metrics.
 * @param {string} cwd
 * @returns {Record<string, {value: number, unit: string, direction: string}>}
 */
export function collectMetrics(cwd) {
  const metrics = {}

  // ── Coverage (vitest json reporter) ───────────────────────────────────────
  run(
    'npx',
    [
      'vitest',
      'run',
      '--coverage',
      '--coverage.reporter=json',
      '--coverage.reportsDirectory=.coverage-tmp',
    ],
    { cwd },
  )
  try {
    const summary = JSON.parse(
      readFileSync(resolve(cwd, '.coverage-tmp/coverage-summary.json'), 'utf-8'),
    )
    metrics.coverageLine = {
      value: summary.total.lines.pct,
      unit: 'percent',
      direction: 'higher-is-better',
    }

    metrics.coverageBranch = {
      value: summary.total.branches?.pct ?? 0,
      unit: 'percent',
      direction: 'higher-is-better',
    }
  } catch {
    metrics.coverageLine = { value: 0, unit: 'percent', direction: 'higher-is-better' }
  }

  // ── ESLint errors (severity 2) ────────────────────────────────────────────
  const eslintRaw = spawnOrSkip(
    'eslintErrors',
    'eslint',
    'npx',
    ['eslint', 'src', '--format', 'json'],
    { cwd },
  )
  if (eslintRaw !== null) {
    try {
      const report = JSON.parse(eslintRaw.stdout || '[]')
      metrics.eslintErrors = {
        value: report.flatMap((f) => f.messages).filter((m) => m.severity === 2).length,
        unit: 'count',
        direction: 'lower-is-better',
      }
    } catch {
      metrics.eslintErrors = { value: 0, unit: 'count', direction: 'lower-is-better' }
    }
  }

  // ── TSC strict errors ─────────────────────────────────────────────────────
  const tscRaw = spawnOrSkip('tscStrictErrors', 'tsc', 'npx', ['tsc', '--noEmit'], { cwd })
  if (tscRaw !== null) {
    const output = (tscRaw.stdout ?? '') + (tscRaw.stderr ?? '')
    metrics.tscStrictErrors = {
      value: output.split('\n').filter((l) => l.includes('error TS')).length,
      unit: 'count',
      direction: 'lower-is-better',
    }
  }

  // ── Complexity violations (eslint rule) ───────────────────────────────────
  const eslintComplexRaw = spawnOrSkip(
    'complexityViolations',
    'eslint',
    'npx',
    ['eslint', 'src', '--format', 'json', '--rule', '{"complexity":["warn",10]}'],
    { cwd },
  )
  if (eslintComplexRaw !== null) {
    try {
      const report = JSON.parse(eslintComplexRaw.stdout || '[]')
      metrics.complexityViolations = {
        value: report.flatMap((f) => f.messages).filter((m) => m.ruleId === 'complexity').length,
        unit: 'count',
        direction: 'lower-is-better',
      }
    } catch {
      metrics.complexityViolations = { value: 0, unit: 'count', direction: 'lower-is-better' }
    }
  }

  // ── Dead code (knip) ──────────────────────────────────────────────────────
  const knipRaw = spawnOrSkip('deadCode', 'knip', 'npx', ['knip', '--reporter', 'json'], { cwd })
  if (knipRaw !== null) {
    try {
      const report = JSON.parse(knipRaw.stdout || '{}')
      metrics.deadCode = {
        value: (report.files ?? []).length + (report.exports ?? []).length,
        unit: 'count',
        direction: 'lower-is-better',
      }
    } catch {
      metrics.deadCode = { value: 0, unit: 'count', direction: 'lower-is-better' }
    }
  }

  // ── Public API surface (library archetype — count of top-level exports) ───
  {
    const grepOut = run('grep', ['-rh', '--include=*.ts', '--include=*.mts', '^export', 'src/'], {
      cwd,
    })
    metrics.publicApiSurface = {
      value: grepOut.stdout ? grepOut.stdout.split('\n').filter(Boolean).length : 0,
      unit: 'count',
      direction: 'lower-is-better',
    }
  }

  return metrics
}
