#!/usr/bin/env node
// debt-report.mjs — generated by arbiter
// Compares current debt metrics against scripts/debt-baseline.json.
// Run from project root: node scripts/debt-report.mjs [--gate] [--require-improvement]
// --gate: exit non-zero if any metric regressed vs baseline
// --require-improvement: exit non-zero if no metric improved (L3 mode)
import { readFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'
import { collectMetrics, countTodos } from './debt-lib.mjs'

function optionValue(name) {
  const index = process.argv.indexOf(name)
  if (index === -1) return undefined
  const value = process.argv[index + 1]
  if (!value || value.startsWith('-')) {
    process.stderr.write(`[arbiter] ${name} requires a value\n`)
    process.exit(2)
  }
  return value
}

const gateMode = process.argv.includes('--gate')
const requireImprovement = process.argv.includes('--require-improvement')
const coverageSummaryPath = optionValue('--coverage-summary')
const coverageStartedAtRaw = optionValue('--coverage-started-at')
const coverageStartedAt =
  coverageStartedAtRaw === undefined ? undefined : Number(coverageStartedAtRaw)
if (coverageStartedAtRaw !== undefined && !Number.isFinite(coverageStartedAt)) {
  process.stderr.write('[arbiter] --coverage-started-at must be a finite epoch timestamp\n')
  process.exit(2)
}
if (coverageSummaryPath !== undefined && coverageStartedAt === undefined) {
  process.stderr.write(
    '[arbiter] --coverage-summary requires --coverage-started-at for stale-report protection\n',
  )
  process.exit(2)
}
const cwd = process.cwd()
const BASELINE_FILE = resolve(cwd, 'scripts/debt-baseline.json')

// ─── Load baseline ────────────────────────────────────────────────────────────
if (!existsSync(BASELINE_FILE)) {
  console.warn(
    '[arbiter] WARN: debt-baseline.json not found.\n  Run: node scripts/capture-debt-baseline.mjs\n  Until baseline is captured, debt ratchet is INACTIVE.',
  )
  process.exit(0)
}

const rawBaseline = JSON.parse(readFileSync(BASELINE_FILE, 'utf-8'))

// ─── Schema version check ─────────────────────────────────────────────────────
if (rawBaseline.version !== 2) {
  const ver = rawBaseline.version ?? 'unknown'
  process.stdout.write(
    `[arbiter] Baseline is schema v${ver}; run: node scripts/capture-debt-baseline.mjs to migrate to v2.\n`,
  )
  process.exit(0)
}

const baseline = rawBaseline

// ─── Collect current metrics ──────────────────────────────────────────────────
// collectionErrors receives tool-RAN-but-collection-failed events (distinct
// from tool-not-installed soft-skips). In --gate mode these are hard failures:
// treating them as "missing tool" would let fileset/config drift silently
// disable a ratchet metric (#1286, fail-closed CANON-22).
const collectionErrors = []
const current = collectMetrics(cwd, collectionErrors, {
  ...(coverageSummaryPath !== undefined ? { coverageSummaryPath } : {}),
  ...(coverageStartedAt !== undefined ? { coverageStartedAt } : {}),
})
current.todoCount = { value: countTodos(cwd), unit: 'count', direction: 'lower-is-better' }

if (collectionErrors.length > 0) {
  for (const e of collectionErrors) {
    process.stdout.write(`[arbiter] collection FAILURE for ${e.metric}: ${e.reason}\n`)
  }
  if (gateMode) {
    process.stdout.write('[arbiter] ❌ debt gate FAILED: metric collection error (fail-closed)\n')
    process.exit(1)
  }
}

// Measurement-noise tolerance for v8-coverage metrics (#2253): CI's v8
// collector measures ~0.2pp lower than a locally-captured baseline on the
// same code (platform/timing variance in which lines v8 marks covered), so a
// strict any-decrease-is-a-regression comparison is structurally prone to a
// first-CI false regression the moment the baseline is captured on a
// different machine than CI (observed: coverageLine -0.16pp, coverageBranch
// -0.22pp — both well under a real change). check-coverage-ratchet.mjs
// (#1483) carries this exact TOLERANCE=0.4 pp noise floor for the
// same v8-jitter reason; mirroring its value here is parity, not invention.
const COVERAGE_NOISE_TOLERANCE_PP = 0.4
const NOISE_TOLERANT_METRICS = new Set(['coverageLine', 'coverageBranch'])

// ─── Compare ──────────────────────────────────────────────────────────────────
const rows = []
let regressions = 0
let improvements = 0

for (const [key, base] of Object.entries(baseline.metrics)) {
  const curr = current[key]
  if (!curr) {
    // Tool missing on this machine — soft warn, never fail gate
    rows.push({
      key,
      base: base.value,
      curr: 'N/A',
      delta: '?',
      status: '⚠️  missing tool',
      unit: base.unit,
      items: base.items ?? [],
    })
    continue
  }
  const delta = curr.value - base.value
  const tolerance = NOISE_TOLERANT_METRICS.has(key) ? COVERAGE_NOISE_TOLERANCE_PP : 0
  let status
  if (base.direction === 'higher-is-better') {
    if (curr.value > base.value) {
      status = '✅ improved'
      improvements++
    } else if (curr.value < base.value - tolerance) {
      status = '❌ regressed'
      regressions++
    } else if (curr.value < base.value) {
      status = '➡️  unchanged (within noise tolerance)'
    } else {
      status = '➡️  unchanged'
    }
  } else {
    if (curr.value < base.value) {
      status = '✅ improved'
      improvements++
    } else if (curr.value > base.value) {
      status = '❌ regressed'
      regressions++
    } else {
      status = '➡️  unchanged'
    }
  }
  rows.push({
    key,
    base: base.value,
    curr: curr.value,
    delta: delta > 0 ? `+${delta.toFixed(1)}` : delta.toFixed(1),
    status,
    unit: base.unit,
    items: base.items ?? [],
  })
}

// New metrics not yet in baseline — informational only
for (const [key, curr] of Object.entries(current)) {
  if (!baseline.metrics[key]) {
    rows.push({
      key,
      base: 'new',
      curr: curr.value,
      delta: 'new',
      status: '✨ new metric',
      unit: curr.unit,
      items: [],
    })
  }
}

// ─── Render report ────────────────────────────────────────────────────────────
process.stdout.write('\n## Debt Ratchet Report\n\n')
process.stdout.write(
  `Baseline: v${baseline.version} — captured ${baseline.capturedAt} @ ${baseline.commit} | archetype: ${baseline.archetype}\n\n`,
)
process.stdout.write('| Metric | Baseline | Current | Delta | Status |\n')
process.stdout.write('|--------|----------|---------|-------|--------|\n')
for (const r of rows) {
  const suffix = r.unit === 'percent' ? '%' : ''
  const baseStr = typeof r.base === 'number' ? `${r.base}${suffix}` : r.base
  const currStr = typeof r.curr === 'number' ? `${r.curr}${suffix}` : r.curr
  process.stdout.write(`| ${r.key} | ${baseStr} | ${currStr} | ${r.delta} | ${r.status} |
`)
  if (r.items && r.items.length > 0) {
    process.stdout.write(`|   ↳ items | \`${r.items.join('`, `')}\` | | | |
`)
  }
}
process.stdout.write('\n')

// ─── Gate enforcement ─────────────────────────────────────────────────────────
if (gateMode && regressions > 0) {
  console.error(`[arbiter] GATE FAIL: ${regressions} metric(s) regressed vs baseline.`)
  process.exit(1)
}
if (requireImprovement && improvements === 0) {
  console.error('[arbiter] GATE FAIL: No metrics improved (--require-improvement mode).')
  process.exit(1)
}
process.exit(0)
