// debt-lib.mjs — generated by arbiter
// Shared metric collection helpers used by capture-debt-baseline.mjs and debt-report.mjs.
// Re-generate with: arbiter update
import { spawnSync } from 'node:child_process'
import {
  readFileSync,
  existsSync,
  readdirSync,
  rmSync,
  mkdirSync,
  chmodSync,
  renameSync,
} from 'node:fs'
import { createRequire } from 'node:module'
import { dirname, join, resolve } from 'node:path'
import { walkRepo } from './lib/glob-walk.mjs'

// The `eslint <paths> --format json` output for this repo exceeds the Node
// spawnSync default maxBuffer (1 MiB); without a raised ceiling the child aborts
// with ENOBUFS, stdout is silently truncated, the JSON fails to parse, and the
// metric collapses to 0 (the dormant complexityViolations ratchet root cause,
// #1542). 64 MiB comfortably covers the full-repo eslint/knip JSON reports.
const RUN_MAX_BUFFER = 64 * 1024 * 1024

function run(cmd, args, opts) {
  return spawnSync(cmd, args, {
    encoding: 'utf-8',
    shell: false,
    maxBuffer: RUN_MAX_BUFFER,
    ...opts,
  })
}

// jscpd v5 ships its scanner as a prebuilt native `cpd` binary selected per
// platform by `jscpd/run-jscpd.js` (#1304). On glibc Linux it installs the
// `cpd-linux-x64-gnu` package, but that binary is built against GLIBC ≥ 2.34;
// on an older CI image (glibc < 2.32) the loader rejects it — exit 1, no report
// — so the duplication scan failed closed even though jscpd "is installed". The
// `cpd-linux-x64-musl` variant is a *static-pie* ELF with no libc dependency, so
// it runs on any Linux regardless of glibc age. npm refuses to install a
// `libc:["musl"]` optional dep on a glibc host, so we materialise it on demand
// from the version-pinned registry into a local cache and run it directly.
const JSCPD_STATIC_PKG = 'cpd-linux-x64-musl'

/**
 * Materialise jscpd's static (musl, libc-independent) `cpd` binary into a local
 * cache and return its path, or null if unavailable (no network / not Linux-x64
 * / npm absent). Idempotent: a cached binary is reused. The version is pinned to
 * the installed jscpd so the static binary always matches the gnu one (#1304).
 * @param {string} jscpdPkgDir - dir of the resolved jscpd package (has version)
 * @returns {string | null}
 */
function resolveStaticCpd(jscpdPkgDir) {
  if (process.platform !== 'linux' || process.arch !== 'x64') return null
  let version
  try {
    version = JSON.parse(readFileSync(join(jscpdPkgDir, 'package.json'), 'utf-8')).version
  } catch {
    return null
  }
  const cacheRoot = resolve(jscpdPkgDir, '..', '.cache', 'jscpd-static', version)
  const cpdPath = join(cacheRoot, 'cpd')
  if (existsSync(cpdPath)) return cpdPath
  // Fetch the version-pinned static package tarball and extract its binary.
  let tmp
  try {
    mkdirSync(cacheRoot, { recursive: true })
    tmp = join(cacheRoot, '.pack')
    mkdirSync(tmp, { recursive: true })
    const pack = run('npm', ['pack', `${JSCPD_STATIC_PKG}@${version}`, '--silent'], { cwd: tmp })
    if ((pack.status ?? 1) !== 0) return null
    const tgz = readdirSync(tmp).find((f) => f.endsWith('.tgz'))
    if (!tgz) return null
    const untar = run('tar', ['xzf', tgz, '-C', tmp], { cwd: tmp })
    if ((untar.status ?? 1) !== 0) return null
    const extracted = join(tmp, 'package', 'cpd-bin', 'cpd')
    if (!existsSync(extracted)) return null
    renameSync(extracted, cpdPath)
    chmodSync(cpdPath, 0o755)
    rmSync(tmp, { recursive: true, force: true })
    return cpdPath
  } catch {
    if (tmp) rmSync(tmp, { recursive: true, force: true })
    return null
  }
}

/**
 * True when a jscpd spawn result is the glibc-too-old failure: the native gnu
 * `cpd` binary loaded but the dynamic linker could not satisfy its GLIBC version
 * requirement (exit 1, empty report, `GLIBC_x.yy not found` on stderr) (#1304).
 * @param {{status: number|null, stderr?: string}} r
 * @returns {boolean}
 */
export function isGlibcIncompatible(r) {
  return (r?.status ?? 0) !== 0 && /GLIBC_[\d.]+'? not found/.test(r?.stderr ?? '')
}

/**
 * Resolve the default jscpd spawn (#1304). jscpd v5 runs a prebuilt native `cpd`
 * binary chosen per platform by `jscpd/run-jscpd.js`. This resolves the installed
 * jscpd launcher and runs it directly with the current node. On the docker-ci-build
 * runner the glibc `cpd-linux-x64-gnu` binary is built against GLIBC ≥ 2.34 but the
 * image's glibc is < 2.32, so the loader rejects it (exit 1, no report) and the scan
 * failed closed even though jscpd is installed. On that glibc-too-old failure the
 * spawn retries once with the static (musl, libc-independent) `cpd` — materialised
 * on demand by resolveStaticCpd — so the scan actually runs and writes a report.
 * If jscpd cannot be resolved at all (greenfield/baseline target without the
 * devDependency) it falls back to the `npx --no-install jscpd` skip-spawn, whose
 * missing-packages result drives the tool-not-installed (`{skipped:true}`) contract.
 *
 * The returned spawn accepts the SAME argv the caller built for the npx path
 * (`['--no-install','jscpd',...paths,'--silent']`); the direct-binary path strips
 * the npx-only `--no-install`/`jscpd` prefix tokens, the fallback passes them
 * through. `resolveBin`, `resolveStatic`, and the per-call `spawnFn` are injectable
 * so tests never shell to a real npx or native binary.
 * @param {string} cwd
 * @param {{resolveBin?: (cwd: string) => string, resolveStatic?: () => string | null}} [opts]
 * @returns {(dir: string, args: string[], callOpts?: {spawnFn?: (cmd: string, args: string[], o: object) => {status: number|null, stdout: string, stderr: string}}) => ({status: number|null, stdout: string, stderr: string} | null)}
 */
export function resolveJscpdSpawn(cwd, opts = {}) {
  const resolveBin =
    opts.resolveBin ??
    ((dir) => {
      // Resolve from the scanned project first (its node_modules), then fall
      // back to this module's own require context — the self repo installs jscpd
      // as a devDependency reachable from here even when the scan dir has no
      // local node_modules (e.g. a temp fixture or a nested workspace).
      let pkgPath
      try {
        pkgPath = createRequire(join(resolve(dir), 'package.json')).resolve('jscpd/package.json')
      } catch {
        pkgPath = createRequire(import.meta.url).resolve('jscpd/package.json')
      }
      const pkg = JSON.parse(readFileSync(pkgPath, 'utf-8'))
      const binEntry = typeof pkg.bin === 'string' ? pkg.bin : pkg.bin?.jscpd
      if (!binEntry) throw new Error('jscpd package.json has no bin.jscpd entry')
      return join(dirname(pkgPath), binEntry)
    })

  let binPath
  try {
    binPath = resolveBin(cwd)
  } catch {
    // jscpd not installed/resolvable — fall back to npx --no-install jscpd, whose
    // ENOENT/"missing packages" result drives jscpdScan's skip contract.
    return (dir, args, callOpts = {}) => {
      const spawnFn = callOpts.spawnFn
      if (spawnFn) return spawnFn('npx', args, { cwd: dir })
      const r = spawnOrSkip('duplicationPercentage', 'jscpd', 'npx', args, { cwd: dir })
      return r === null ? null : r
    }
  }

  const jscpdPkgDir = dirname(binPath)
  const resolveStatic = opts.resolveStatic ?? (() => resolveStaticCpd(jscpdPkgDir))
  // Direct binary: drop the npx-only prefix tokens so jscpd sees only its own
  // positional args (paths + flags). The launcher (run-jscpd.js) selects the
  // platform-native `cpd`; if that binary is glibc-incompatible on this runner
  // (#1304) retry once with the static (musl, libc-independent) `cpd` so the
  // scan ACTUALLY runs and writes a report — fail-closed stays intact when even
  // the static binary is unavailable (the error path is unchanged).
  return (dir, args, callOpts = {}) => {
    const jscpdArgs = args.filter((a) => a !== '--no-install' && a !== 'jscpd')
    const spawnFn = callOpts.spawnFn ?? ((cmd, a, o) => run(cmd, a, o))
    const r = spawnFn(process.execPath, [binPath, ...jscpdArgs], { cwd: dir })
    if (!isGlibcIncompatible(r)) return r
    const staticCpd = resolveStatic()
    if (!staticCpd) return r
    return spawnFn(staticCpd, jscpdArgs, { cwd: dir })
  }
}

/**
 * Run a command. If the binary is not installed (ENOENT), log a warning to
 * stderr and return null. Callers skip null-result metrics entirely.
 * @param {string} name - metric key for the warning message
 * @param {string} tool - human name of the missing tool
 * @param {string} cmd  - executable
 * @param {string[]} args
 * @param {object} [opts]
 * @returns {import('child_process').SpawnSyncReturns<string> | null}
 */
export function spawnOrSkip(name, tool, cmd, args, opts) {
  const r = run(cmd, args, opts ?? {})
  if (r.error?.code === 'ENOENT') {
    process.stderr.write(`[baseline] skip ${name} — ${tool} not installed\n`)
    return null
  }
  return r
}

/**
 * Fail-closed jscpd v5 scan (#1286). jscpd v5 silently ignores the config
 * `pattern`/`path` keys and exits 0 on a 0-file scan, writing a 0% report —
 * so the fileset MUST be passed as positional CLI args. `.jscpd.json#path`
 * is the script-private SSOT for that fileset (jscpd itself disregards the
 * key; this helper and check-duplication.mjs read it).
 * A scan that ran but covered 0 sources is an ERROR, never a recorded 0%.
 * @param {string} cwd
 * @param {{spawn?: (cwd: string, args: string[]) => {status: number|null, stdout: string, stderr: string}}} [opts]
 *   spawn is injectable for tests; production default shells `npx --no-install jscpd`.
 * @returns {{error?: string, skipped?: boolean, legacyNoReport?: boolean, status?: number, sources?: number, percentage?: number}}
 */
export function jscpdScan(cwd, opts = {}) {
  const configPath = resolve(cwd, '.jscpd.json')
  let cfg
  try {
    cfg = JSON.parse(readFileSync(configPath, 'utf-8'))
  } catch (err) {
    return { error: `.jscpd.json unreadable at ${configPath}: ${err.message}` }
  }
  const paths = Array.isArray(cfg.path) ? cfg.path.filter((p) => typeof p === 'string' && p) : []
  if (paths.length === 0) {
    return {
      error: cfg.pattern
        ? 'legacy v4 .jscpd.json: `pattern` is silently ignored by jscpd v5 — ' +
          'replace it with a "path" array (the scan fileset, passed as positional args). See #1286.'
        : '.jscpd.json has no "path" array — required as the jscpd v5 fileset SSOT (#1286).',
    }
  }
  // Without the json reporter, v5 exits 0 writing no report — indistinguishable
  // from the v4 zero-clones case, so exit-0-plus-no-report could no longer be
  // trusted as a v4 signal. Reject the config up front (fail-closed, #1286).
  if (!Array.isArray(cfg.reporters) || !cfg.reporters.includes('json')) {
    return {
      error:
        '.jscpd.json "reporters" must include "json" — the scan is parsed from report/jscpd-report.json (#1286).',
    }
  }
  // Honor a custom `output` dir; default matches jscpd's `report/`.
  const reportPath = resolve(
    cwd,
    typeof cfg.output === 'string' ? cfg.output : 'report',
    'jscpd-report.json',
  )
  // Stale-report poisoning guard: a leftover report from a previous run must
  // never be parsed as if it were produced by this invocation.
  rmSync(reportPath, { force: true })
  const spawn = opts.spawn ?? resolveJscpdSpawn(cwd)
  const r = spawn(cwd, ['--no-install', 'jscpd', ...paths, '--silent'])
  if (r === null) return { skipped: true }
  // `npx --no-install` exits 1 (not ENOENT) when the package is absent — that is
  // the tool-not-installed case (greenfield target without jscpd), same contract
  // as spawnOrSkip: skip the collector, never a failed-scan error.
  if ((r.status ?? 0) !== 0 && /npx canceled due to missing packages/.test(r.stderr ?? '')) {
    process.stderr.write('[baseline] skip duplicationPercentage — jscpd not installed\n')
    return { skipped: true }
  }
  if (!existsSync(reportPath)) {
    if ((r.status ?? 0) === 0) {
      // jscpd v4 writes the json report only when clones exist; v5 always
      // writes it. Exit 0 + no report can only be a v4 binary (brownfield
      // project not yet bumped) with zero clones.
      return { legacyNoReport: true, status: 0 }
    }
    // Surface jscpd's own stderr so the cause is visible in the gate output
    // (e.g. a glibc-too-old runner image, #1304) instead of an opaque exit code.
    const why = (r.stderr ?? '').trim().split('\n').slice(0, 3).join(' | ')
    return {
      error:
        `jscpd failed (exit ${r.status}) and wrote no report — fail-closed (#1286)` +
        (why ? `: ${why}` : ''),
    }
  }
  let dup
  try {
    dup = JSON.parse(readFileSync(reportPath, 'utf-8'))
  } catch (err) {
    return { error: `jscpd report unreadable: ${err.message}` }
  }
  const total = dup.statistics?.total ?? {}
  const sources = total.sources ?? 0
  if (sources === 0) {
    return {
      error:
        'jscpd scanned 0 source files — fileset/config drift; refusing to record 0% ' +
        '(fail-closed, CANON-22 / #1286). Check .jscpd.json "path" entries exist.',
      status: r.status ?? 0,
    }
  }
  if (typeof total.percentage !== 'number') {
    return {
      error:
        'jscpd report has no numeric statistics.total.percentage — schema drift; refusing to record 0% (#1286).',
    }
  }
  return { status: r.status ?? 0, sources, percentage: total.percentage }
}

/**
 * Baseline key-drop guard (#1286): a recapture must never silently delete a
 * metric that the prior baseline tracked (e.g. a jscpd hiccup during capture
 * would otherwise remove duplicationPercentage and disable the ratchet).
 * New keys are always allowed.
 * @param {Record<string, unknown>} priorMetrics
 * @param {Record<string, unknown>} nextMetrics
 */
export function assertKeyParity(priorMetrics, nextMetrics) {
  const dropped = Object.keys(priorMetrics ?? {}).filter((k) => !(k in (nextMetrics ?? {})))
  if (dropped.length > 0) {
    throw new Error(
      `baseline recapture would drop metric(s): ${dropped.join(', ')} — ` +
        'refusing to write (fail-closed). Fix the collector or remove the key deliberately.',
    )
  }
}

/**
 * Count TO-DO markers across common source file extensions in cwd.
 * Uses walkRepo (glob-walk.mjs) instead of raw `grep -r .` so nested worktree
 * checkouts (e.g. `.claude/worktrees/**`) are never double-counted (#1734/#1752).
 * @param {string} cwd
 * @returns {number}
 */
export function countTodos(cwd) {
  const MARKER_EXTENSIONS = new Set(['.js', '.ts', '.java', '.go', '.py', '.rs'])
  const EXTRA_SKIP_SEGMENTS = new Set(['target', '.arbiter', '.temp'])
  // arbiter-suppress(INV-21, until=2099-01-01, reason="self-referential marker regex inside the TODO-counting collector itself, not an unresolved TODO", owner=@luca)
  const MARKER_RE = /\bTODO\b/
  let count = 0
  for (const rel of walkRepo(cwd)) {
    const dot = rel.lastIndexOf('.')
    if (dot === -1 || !MARKER_EXTENSIONS.has(rel.slice(dot))) continue
    if (rel.split('/').some((seg) => EXTRA_SKIP_SEGMENTS.has(seg))) continue
    try {
      const lines = readFileSync(resolve(cwd, rel), 'utf-8').split('\n')
      count += lines.filter((l) => MARKER_RE.test(l)).length
    } catch {
      /* skip unreadable files */
    }
  }
  return count
}

// ── Finding-hygiene metrics (#1405) ──────────────────────────────────────────
// The incidental-findings spool (`.arbiter/findings/*.jsonl`, #1401) is the SSOT
// for un-promoted findings. These metrics make the debt ratchet reward DRAINING
// the spool (lower-is-better) and never let merely FILING findings inflate a
// green signal (anti-gaming, INV-114). Spool ABSENT → both metrics are OMITTED
// (treated as not-applicable / "missing tool"), NEVER recorded as a regression.

/** Relative path of the per-shard findings spool directory (#1401). */
const FINDINGS_DIR = '.arbiter/findings'

/**
 * Read the findings spool and return open (un-promoted) finding metrics.
 * Returns `{}` when the spool directory is absent (metric omitted = NA, never a
 * regression). When present:
 *   - openFindingsCount    — distinct fingerprints across all shards (dedup-safe)
 *   - unpromotedFindingsAge — age in whole days of the OLDEST open finding (0 when drained)
 * Malformed JSONL lines are skipped; a missing/empty spool yields count 0, age 0.
 * @param {string} cwd
 * @returns {Record<string, {value: number, unit: string, direction: string}>}
 */
export function collectFindingsMetrics(cwd) {
  const findingsDir = resolve(cwd, FINDINGS_DIR)
  if (!existsSync(findingsDir)) return {}
  let shards
  try {
    shards = readdirSync(findingsDir).filter((f) => f.endsWith('.jsonl'))
  } catch {
    return {}
  }
  const fingerprints = new Set()
  let oldestTs = null
  for (const shard of shards) {
    let text
    try {
      text = readFileSync(join(findingsDir, shard), 'utf-8')
    } catch {
      continue
    }
    for (const line of text.split('\n')) {
      const trimmed = line.trim()
      if (trimmed.length === 0) continue
      let entry
      try {
        entry = JSON.parse(trimmed)
      } catch {
        continue // malformed line — resilient skip
      }
      if (entry === null || typeof entry !== 'object') continue
      const fp = typeof entry.fingerprint === 'string' ? entry.fingerprint : trimmed
      fingerprints.add(fp)
      const ts = typeof entry.ts === 'string' ? Date.parse(entry.ts) : NaN
      if (!Number.isNaN(ts) && (oldestTs === null || ts < oldestTs)) oldestTs = ts
    }
  }
  const ageDays =
    oldestTs === null ? 0 : Math.floor((Date.now() - oldestTs) / (24 * 60 * 60 * 1000))
  return {
    openFindingsCount: {
      value: fingerprints.size,
      unit: 'count',
      direction: 'lower-is-better',
    },
    unpromotedFindingsAge: {
      value: ageDays < 0 ? 0 : ageDays,
      unit: 'days',
      direction: 'lower-is-better',
    },
  }
}

/**
 * Return the short git commit hash for HEAD, or 'unknown'.
 * @param {string} cwd
 * @returns {string}
 */
export function getCommit(cwd) {
  const r = run('git', ['rev-parse', '--short', 'HEAD'], { cwd })
  return r.status === 0 ? r.stdout.trim() : 'unknown'
}

// ─── Per-stack metric collectors ─────────────────────────────────────────────
// Each language block exports a single `collectMetrics(cwd)` function.
// EJS conditionals select the correct block at generation time.

/**
 * Collect TypeScript/JavaScript debt metrics.
 * @param {string} cwd
 * @param {Array<{metric: string, reason: string}>} [collectionErrors]
 *   Sink for tool-ran-but-collection-failed events (distinct from
 *   tool-not-installed, which soft-skips). debt-report --gate hard-fails on
 *   any entry (#1286, fail-closed).
 * @returns {Record<string, {value: number, unit: string, direction: string}>}
 */
export function collectMetrics(cwd, collectionErrors = []) {
  const metrics = {}

  // ── Coverage (vitest json reporter) ───────────────────────────────────────
  run(
    'npx',
    [
      'vitest',
      'run',
      '--coverage',
      '--coverage.reporter=json',
      '--coverage.reportsDirectory=.coverage-tmp',
    ],
    { cwd },
  )
  try {
    const summary = JSON.parse(
      readFileSync(resolve(cwd, '.coverage-tmp/coverage-summary.json'), 'utf-8'),
    )
    metrics.coverageLine = {
      value: summary.total.lines.pct,
      unit: 'percent',
      direction: 'higher-is-better',
    }

    metrics.coverageBranch = {
      value: summary.total.branches?.pct ?? 0,
      unit: 'percent',
      direction: 'higher-is-better',
    }
  } catch {
    metrics.coverageLine = { value: 0, unit: 'percent', direction: 'higher-is-better' }
  }

  // ── ESLint errors (severity 2) ────────────────────────────────────────────
  const eslintRaw = spawnOrSkip(
    'eslintErrors',
    'eslint',
    'npx',
    ['eslint', 'src', '--format', 'json'],
    { cwd },
  )
  if (eslintRaw !== null) {
    try {
      const report = JSON.parse(eslintRaw.stdout || '[]')
      metrics.eslintErrors = {
        value: report.flatMap((f) => f.messages).filter((m) => m.severity === 2).length,
        unit: 'count',
        direction: 'lower-is-better',
      }
    } catch {
      metrics.eslintErrors = { value: 0, unit: 'count', direction: 'lower-is-better' }
    }
  }

  // ── TSC strict errors ─────────────────────────────────────────────────────
  const tscRaw = spawnOrSkip('tscStrictErrors', 'tsc', 'npx', ['tsc', '--noEmit'], { cwd })
  if (tscRaw !== null) {
    const output = (tscRaw.stdout ?? '') + (tscRaw.stderr ?? '')
    metrics.tscStrictErrors = {
      value: output.split('\n').filter((l) => l.includes('error TS')).length,
      unit: 'count',
      direction: 'lower-is-better',
    }
  }

  // ── Complexity violations (eslint rule) ───────────────────────────────────
  // Scan `scripts` alongside `src`: the gate-enforcement layer is the
  // highest-leverage code in the repo and was previously exempt from the
  // complexity ratchet (#1523/#1542). The baseline grandfathers the current
  // offenders; the ratchet blocks any net increase and admits gradual burn-down.
  const eslintComplexRaw = spawnOrSkip(
    'complexityViolations',
    'eslint',
    'npx',
    ['eslint', 'src', 'scripts', '--format', 'json', '--rule', '{"complexity":["warn",10]}'],
    { cwd },
  )
  if (eslintComplexRaw !== null) {
    try {
      const report = JSON.parse(eslintComplexRaw.stdout || '[]')
      metrics.complexityViolations = {
        value: report.flatMap((f) => f.messages).filter((m) => m.ruleId === 'complexity').length,
        unit: 'count',
        direction: 'lower-is-better',
      }
    } catch {
      metrics.complexityViolations = { value: 0, unit: 'count', direction: 'lower-is-better' }
    }
  }

  // ── Dead code (knip) ──────────────────────────────────────────────────────
  const knipRaw = spawnOrSkip('deadCode', 'knip', 'npx', ['knip', '--reporter', 'json'], { cwd })
  if (knipRaw !== null) {
    try {
      const report = JSON.parse(knipRaw.stdout || '{}')
      metrics.deadCode = {
        value: (report.files ?? []).length + (report.exports ?? []).length,
        unit: 'count',
        direction: 'lower-is-better',
      }
    } catch {
      metrics.deadCode = { value: 0, unit: 'count', direction: 'lower-is-better' }
    }
  }

  // ── Duplication (jscpd) — CANON-22 DRY ratchet (Lehman entropy) ────────────
  // jscpdScan handles the v5 fileset contract (positional paths from
  // .jscpd.json#path, stale-report cleanup, 0-source rejection). A scan that
  // ran but failed is surfaced via collectionErrors so debt-report --gate can
  // hard-fail instead of soft-skipping as "missing tool" (#1286, fail-closed).
  {
    const scan = jscpdScan(cwd)
    if (scan.skipped) {
      // npx/tooling absent on this machine — genuine soft-skip (ENOENT path).
    } else if (scan.error) {
      collectionErrors.push({ metric: 'duplicationPercentage', reason: scan.error })
      process.stderr.write(`[baseline] ERROR: ${scan.error}\n`)
    } else if (scan.legacyNoReport) {
      // v4 binary, zero clones (v5 always writes the report) — genuinely 0%.
      metrics.duplicationPercentage = { value: 0, unit: 'percent', direction: 'lower-is-better' }
    } else {
      metrics.duplicationPercentage = {
        value: scan.percentage,
        unit: 'percent',
        direction: 'lower-is-better',
      }
    }
  }

  // ── Public API surface (library archetype — count of top-level exports) ───
  {
    const grepOut = run('grep', ['-rh', '--include=*.ts', '--include=*.mts', '^export', 'src/'], {
      cwd,
    })
    metrics.publicApiSurface = {
      value: grepOut.stdout ? grepOut.stdout.split('\n').filter(Boolean).length : 0,
      unit: 'count',
      direction: 'lower-is-better',
    }
  }

  // ── Finding-hygiene (un-promoted findings spool, #1405) ───────────────────
  // Language-agnostic: reads `.arbiter/findings/*.jsonl`. Spool absent → omitted
  // (NA), so a project that never filed a finding is not penalised. Rewards
  // DRAINING (lower-is-better); filing more findings is a regression (anti-gaming).
  Object.assign(metrics, collectFindingsMetrics(cwd))

  return metrics
}
