#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// scripts/check-assertion-delta.mjs — generated by arbiter (anti-fake-green, #2161).
//
// CATALOG: diffs the current commit range for test files that remove an assertion with none
// CATALOG:   added, or raise the skip-marker count, without an Assertion-Delta-Override trailer.
// CATALOG: rejected fold-in into check-muted-test.mjs because that inspects the CURRENT tree for a
// CATALOG:   skip marker; this inspects a DIFF for a removed assertion or a rising skip delta — a
// CATALOG:   different axis (snapshot content vs change-over-range).
// CATALOG: rejected fold-in into check-commit-footer-rationale.mjs because that walks commit-touched
// CATALOG:   FILE PATTERNS (trivyignore/suppressions/*); this walks DIFF CONTENT of test files —
// CATALOG:   the trailer-override shape is reused, the detection surface is not.
//
// Assertion-delta guard. ImpossibleBench (arxiv 2510.20270) found that the reward-hacking exploit
// models reach for most often is editing the test itself — removing an assertion, or adding a
// skip — while the surrounding CI turns green. A regex over the diff is cheaper and harder to game
// than an LLM judge for this specific shape: on the current commit range, if a touched test file's
// diff REMOVES an assertion line with NO assertion line added anywhere in the same range, or the
// skip-marker count (@Disabled/.skip/xit/fixme) goes UP, that is reward-hacking-shaped and the gate
// fails asking for an explicit justification. A refactor that moves/rewrites assertions (net delta
// >= 0) is unaffected — this is a delta gate, not a line-count minimum.
//
// Override: an `Assertion-Delta-Override: <reason>` trailer on the tip commit of the range makes the
// gate pass (logged, not silent) — same commit-footer-trailer shape as INV-119, so the override
// lands in ordinary commit-message audit trail rather than a separate suppression file.
//
// Range determination mirrors check-commit-footer-rationale.mjs (INV-119): defaults to
// `origin/main..HEAD`, fails OPEN (exit 0, explicit WARN) only when the range itself cannot be
// resolved (e.g. no `origin` remote in a fresh clone) — never a silent swallow, always logged.
//
// Exit codes (INV-53): 0=PASS/override/vacuous/no-range, 1=FAIL, 2=ERROR (self).
// Usage: node scripts/check-assertion-delta.mjs [--range=<ref>] [--repo-root=<path>] [--evidence-dir=<path>] [--help]
import { execFileSync } from 'node:child_process'
import { writeFileSync, mkdirSync } from 'node:fs'
import { resolve, join } from 'node:path'

const HELP = [
  'Usage: node scripts/check-assertion-delta.mjs [options]',
  '',
  'Fails when a diff removes test assertions with none added, or increases the skip-marker count,',
  'without an Assertion-Delta-Override trailer on the tip commit.',
  '',
  'Options:',
  '  --range=<ref>          Git range to scan (default: origin/main..HEAD)',
  '  --repo-root=<path>     Repository root to run git in (default: cwd)',
  '  --evidence-dir=<path>  Directory to write the evidence artifact',
  '  --help, -h             Show this help and exit',
].join('\n')

// Assertion patterns per stack (AC-3: a data table, not hardcoded in the walk logic).
const ASSERTION_PATTERNS = [
  { stack: 'vitest-jest-playwright', re: /\bexpect\s*\(/ },
  {
    stack: 'junit-assertj',
    re: /\bassert(?:That|Equals|True|False|Null|NotNull|ArrayEquals|Throws)\s*\(|\bAssertions\.\w+\s*\(/,
  },
]

// Skip-marker patterns — a rising count is the other reward-hacking shape (increasing xit/@Disabled).
const SKIP_MARKER_RE = /@Disabled\b|\.skip\s*\(|\bxit\s*\(|\bxtest\s*\(|\bxdescribe\s*\(|\bfixme\b/

// Test files this guard considers in scope.
const TEST_FILE_RE = /\.(?:spec|test)\.(?:ts|tsx|js|jsx|mjs)$|(?:Test|Tests)\.java$/

function parseArgs() {
  const raw = process.argv.slice(2)
  let range = 'origin/main..HEAD'
  let repoRoot = process.cwd()
  let evidenceDir = null
  let help = false
  for (let i = 0; i < raw.length; i++) {
    const arg = raw[i]
    if (arg === '--help' || arg === '-h') help = true
    else if (arg.startsWith('--range=')) range = arg.slice('--range='.length)
    else if (arg === '--range' && i + 1 < raw.length) range = raw[++i]
    else if (arg.startsWith('--repo-root=')) repoRoot = resolve(arg.slice('--repo-root='.length))
    else if (arg === '--repo-root' && i + 1 < raw.length) repoRoot = resolve(raw[++i])
    else if (arg.startsWith('--evidence-dir=')) evidenceDir = resolve(arg.slice('--evidence-dir='.length))
    else if (arg === '--evidence-dir' && i + 1 < raw.length) evidenceDir = resolve(raw[++i])
  }
  if (!evidenceDir) evidenceDir = join(repoRoot, '.arbiter', 'evidence', 'assertion-delta')
  return { range, repoRoot, evidenceDir, help }
}

function git(repoRoot, args) {
  return execFileSync('git', args, { cwd: repoRoot, encoding: 'utf-8' })
}

/** Test files touched in `range`, filtered to TEST_FILE_RE. Returns null if the range can't be resolved. */
function changedTestFiles(repoRoot, range) {
  try {
    return git(repoRoot, ['diff', '--name-only', range])
      .trim()
      .split('\n')
      .filter(Boolean)
      .filter((f) => TEST_FILE_RE.test(f))
    // FAIL-OPEN-INTENT: range unresolvable (no origin remote) — caller logs a WARN + exits 0 (SKIP).
  } catch {
    return null
  }
}

/** Count assertion/skip-marker lines added vs removed for one file's diff in `range`. */
function fileDelta(repoRoot, range, file) {
  let diff
  try {
    diff = git(repoRoot, ['diff', '--unified=0', range, '--', file])
    // FAIL-OPEN-INTENT: one file's diff failing degrades to a zero delta for THAT file only.
  } catch {
    return { assertionsAdded: 0, assertionsRemoved: 0, skipAdded: 0, skipRemoved: 0 }
  }
  let assertionsAdded = 0,
    assertionsRemoved = 0,
    skipAdded = 0,
    skipRemoved = 0
  for (const line of diff.split('\n')) {
    if (line.startsWith('+++') || line.startsWith('---') || line.startsWith('@@')) continue
    const added = line.startsWith('+')
    const removed = line.startsWith('-')
    if (!added && !removed) continue
    const body = line.slice(1)
    const isAssertion = ASSERTION_PATTERNS.some((p) => p.re.test(body))
    const isSkip = SKIP_MARKER_RE.test(body)
    if (isAssertion) added ? assertionsAdded++ : assertionsRemoved++
    if (isSkip) added ? skipAdded++ : skipRemoved++
  }
  return { assertionsAdded, assertionsRemoved, skipAdded, skipRemoved }
}

/**
 * Every commit message in `range`, so an override trailer on ANY commit of the range is honored —
 * not just the tip. Mirrors check-commit-footer-rationale.mjs (INV-119), which scans the whole
 * range rather than only HEAD: a reviewer amending/rewording only the tip to add a trailer is not
 * how commit history normally works, and requiring it would make the override impossible to use
 * without a rebase.
 */
function rangeMessages(repoRoot, range) {
  try {
    return git(repoRoot, ['log', '--format=%B%x00', range])
    // FAIL-OPEN-INTENT: unresolvable range → no messages read → no override found (fail-CLOSED).
  } catch {
    return ''
  }
}

const OVERRIDE_RE = /^Assertion-Delta-Override:\s*\S.*$/m

function writeEvidence(evidenceDir, data) {
  try {
    mkdirSync(evidenceDir, { recursive: true })
    const ts = new Date().toISOString().replace(/[:.]/g, '-')
    writeFileSync(join(evidenceDir, `${ts}.json`), JSON.stringify(data, null, 2) + '\n')
  } catch (err) {
    process.stderr.write(
      `check-assertion-delta: WARN — could not write evidence: ${err instanceof Error ? err.message : String(err)}\n`,
    )
  }
}

function main() {
  const { range, repoRoot, evidenceDir, help } = parseArgs()
  if (help) {
    process.stdout.write(HELP + '\n')
    return 0
  }

  const files = changedTestFiles(repoRoot, range)
  if (files === null) {
    process.stderr.write(
      `check-assertion-delta: WARN — range '${range}' could not be resolved (origin unreachable?). Skipping.\n`,
    )
    writeEvidence(evidenceDir, {
      schema: 'arbiter-assertion-delta-v1',
      generated_at: new Date().toISOString(),
      range,
      result: 'SKIP',
      note: 'git range unavailable',
    })
    return 0
  }
  if (files.length === 0) {
    process.stdout.write('check-assertion-delta: OK — no test files touched in range.\n')
    writeEvidence(evidenceDir, {
      schema: 'arbiter-assertion-delta-v1',
      generated_at: new Date().toISOString(),
      range,
      files_scanned: 0,
      result: 'PASS',
    })
    return 0
  }

  let assertionsAdded = 0,
    assertionsRemoved = 0,
    skipAdded = 0,
    skipRemoved = 0
  for (const f of files) {
    const d = fileDelta(repoRoot, range, f)
    assertionsAdded += d.assertionsAdded
    assertionsRemoved += d.assertionsRemoved
    skipAdded += d.skipAdded
    skipRemoved += d.skipRemoved
  }

  const violations = []
  if (assertionsRemoved > 0 && assertionsAdded === 0) {
    violations.push(
      `${assertionsRemoved} assertion(s) removed across ${files.length} test file(s), none added`,
    )
  }
  if (skipAdded > skipRemoved) {
    violations.push(`skip-marker count increased (+${skipAdded} / -${skipRemoved})`)
  }

  const message = rangeMessages(repoRoot, range)
  const overridden = violations.length > 0 && OVERRIDE_RE.test(message)

  const result = violations.length === 0 ? 'PASS' : overridden ? 'OVERRIDDEN' : 'FAIL'
  writeEvidence(evidenceDir, {
    schema: 'arbiter-assertion-delta-v1',
    generated_at: new Date().toISOString(),
    range,
    files_scanned: files.length,
    assertions_added: assertionsAdded,
    assertions_removed: assertionsRemoved,
    skip_added: skipAdded,
    skip_removed: skipRemoved,
    violations,
    result,
  })

  if (violations.length === 0) {
    process.stdout.write(`check-assertion-delta: OK — ${files.length} test file(s) scanned, no reward-hacking shape.\n`)
    return 0
  }
  if (overridden) {
    process.stdout.write(
      `check-assertion-delta: OVERRIDDEN — ${violations.join('; ')} — Assertion-Delta-Override trailer present.\n`,
    )
    return 0
  }
  process.stderr.write(`check-assertion-delta: FAIL — ${violations.join('; ')}\n`)
  process.stderr.write(
    '  If this is a legitimate refactor, add a trailer to the tip commit: ' +
      'Assertion-Delta-Override: <reason>\n',
  )
  return 1
}

try {
  process.exit(main())
} catch (e) {
  process.stderr.write(`check-assertion-delta: ERROR — ${e?.message ?? e}\n`)
  process.exit(2)
}
