#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// scripts/check-doc-set.mjs — generated by arbiter (#1428).
// Doc-set presence audit runner for this project.
// Delegates to the root-local `arbiter doc-set` CLI (no `yaml` dep —
// the engine runs inside arbiter's own environment against this repo).
//
// Usage: node scripts/check-doc-set.mjs [--check] [--strict] [--json] [--generate] [--help]
//
// Exit codes (INV-53): 0=PASS/advisory, 1=FAIL (missing mandatory under --strict), 2=ERROR.
// When invoked by check-all.mjs (advisory, L2) the exit code is informational; the
// gate never hard-fails on the doc-set result alone. Plain --check runs the engine in its
// default advisory mode and exits 0 (no day-1 redness); the strict hard guard is opt-in.
import { runLocalArbiter } from './lib/run-helpers.mjs'

const args = process.argv.slice(2)

process.exit(runLocalArbiter(['doc-set', ...args]))
