#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// scripts/gold-audit.mjs — generated by arbiter (#1419).
// Gold-audit no-regress runner for this project.
// Delegates to `arbiter gold-audit` via npx (no local install, no `yaml` dep —
// the engine runs inside arbiter's own environment against this repo).
//
// Usage: node scripts/gold-audit.mjs [--check] [--stack <s>] [--class <c>] [--json] [--help]
//
// Exit codes (INV-53): 0=PASS/bootstrap, 1=FAIL (score regressed), 2=ERROR.
// When invoked by check-all.mjs (advisory) the exit code is informational; the
// gate never hard-fails on the gold-audit result alone. Plain --check bootstraps a
// missing baseline and exits 0 (no day-1 redness); the strict require-baseline
// hard guard is arbiter-self only and is intentionally never passed here.
import { spawnSync } from 'node:child_process'

const args = process.argv.slice(2)

const result = spawnSync('npx', ['--no-install', 'arbiter', 'gold-audit', ...args], {
  stdio: 'inherit',
  encoding: 'utf-8',
})

if (result.error) {
  process.stderr.write(
    `[gold-audit] spawn error: ${result.error.message}\n`,
  )
  process.exit(2)
}

process.exit(result.status ?? 1)
