#!/usr/bin/env bash
# setup-repo.sh: idempotent GitHub repo initialization
# Generated by arbiter — run once after cloning: bash scripts/setup-repo.sh
set -e

command -v gh >/dev/null 2>&1 || {
  echo "ERROR: gh CLI not found. Install from https://cli.github.com/" >&2
  exit 1
}

gh auth status >/dev/null 2>&1 || {
  echo "ERROR: gh CLI not authenticated. Run: gh auth login" >&2
  exit 1
}

REPO="$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null)" || {
  echo "ERROR: not inside a GitHub repository. Run from the repo root." >&2
  exit 1
}

echo "Setting up repository: $REPO"

# ── Labels ──────────────────────────────────────────────────────────────────

create_label() {
  local name="$1" color="$2" description="$3"
  gh label create "$name" --color "$color" --description "$description" --force 2>/dev/null || true
}

echo "Creating labels..."
create_label "task"        "0075ca" "Tracked work item"
create_label "bug"         "d73a4a" "Something isn't working"
create_label "enhancement" "a2eeef" "New feature or request"
create_label "docs"        "0052cc" "Documentation only"
create_label "in-progress" "fbca04" "Work in progress"
create_label "in-review"   "e4e669" "Under review"

# ── Branch protection ────────────────────────────────────────────────────────

echo "Applying branch protection to main..."
gh api \
  --method PUT \
  "repos/$REPO/branches/main/protection" \
  --field "required_status_checks[strict]=true" \
  --field "required_status_checks[contexts][]=ci" \
  --field "enforce_admins=false" \
  --field "required_pull_request_reviews[required_approving_review_count]=1" \
  --field "restrictions=null" \
  --field "allow_force_pushes=false" \
  --field "allow_deletions=false" \
  2>/dev/null || echo "WARN: branch protection requires admin access — skipped"

# ── Initial milestone ────────────────────────────────────────────────────────

echo "Creating milestone v0.1.0..."
gh api \
  --method POST \
  "repos/$REPO/milestones" \
  --field "title=v0.1.0" \
  --field "description=Initial release" \
  2>/dev/null || true

echo "Done. Repository $REPO is initialized."
