#!/bin/sh
# run.sh — thin shim so hooks, CI, and contributors call the same command.
# Generated by arbiter (INV-87). Pass any check-all.mjs subcommand as $1.
set -e
exec node scripts/check-all.mjs "$@"
