#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// scripts/check-doc-set.mjs — generated by arbiter (#1428).
// Doc-set presence audit runner for this project.
// Delegates to `arbiter doc-set` via npx (no local install, no `yaml` dep —
// the engine runs inside arbiter's own environment against this repo).
//
// Usage: node scripts/check-doc-set.mjs [--check] [--strict] [--json] [--generate] [--help]
//
// Exit codes (INV-53): 0=PASS/advisory, 1=FAIL (missing mandatory under --strict), 2=ERROR.
// When invoked by check-all.mjs (advisory, L2) the exit code is informational; the
// gate never hard-fails on the doc-set result alone. Plain --check runs the engine in its
// default advisory mode and exits 0 (no day-1 redness); the strict hard guard is opt-in.
import { spawnSync } from 'node:child_process'

const args = process.argv.slice(2)

const result = spawnSync('npx', ['--no-install', 'arbiter', 'doc-set', ...args], {
  stdio: 'inherit',
  encoding: 'utf-8',
})

if (result.error) {
  process.stderr.write(
    `[doc-set] spawn error: ${result.error.message}\n`,
  )
  process.exit(2)
}

process.exit(result.status ?? 1)
