#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// scripts/conformance.mjs — generated by arbiter (#1398, INV-128).
// Advisory conformance-scorecard runner for this project.
//
// Self-contained (INV-96 fail-closed): the standalone `arbiter conformance` command
// was retired, so this runner no longer shells out to it. The governance scorecard
// now lives in `arbiter gold-audit` (level band + missing items); this script points
// at it and exits 0. Wired as an advisory (runWarnCheck) in check-all.mjs L2 — it
// never hard-fails the gate.
//
// Usage: node scripts/conformance.mjs [--check] [--help]
// Exit codes (INV-53): 0=advisory OK, 2=ERROR.

try {
  const args = process.argv.slice(2)

  if (args.includes('--help') || args.includes('-h')) {
    process.stdout.write(
      'Usage: node scripts/conformance.mjs [--check]\n' +
        'Advisory runner. Run `npx @arbiter/cli gold-audit` for the governance scorecard.\n',
    )
    process.exit(0)
  }

  process.stdout.write(
    '[conformance] advisory: the standalone conformance command was retired — run ' +
      '`npx @arbiter/cli gold-audit` for the governance scorecard (level band + missing items).\n',
  )
  process.exit(0)
} catch (err) {
  // Fail-closed (INV-96): an unexpected error must block, never silently pass.
  process.stderr.write(
    `[conformance] unexpected error: ${err instanceof Error ? err.stack : String(err)}\n`,
  )
  process.exit(1)
}
