name: Nightly (T4)

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

concurrency:
  group: nightly
  cancel-in-progress: false

jobs:
  nightly:
    name: Nightly jobs
    uses: ./.github/workflows/_nightly.yml
    permissions:
      contents: read
      issues: write
    secrets: inherit
